version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      time: "20:00"
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: "/.github/workflows"
    schedule:
      interval: weekly
      time: "20:00"
    open-pull-requests-limit: 10
