name: "Label Syncer Reloaded"
description: "Sync GitHub labels in the declarative way."
author: "brpaz"
inputs:
  manifest:
    description: "File path of YAML manifest for labels"
    required: false
    default: ".github/labels.yml"
  repository:
    description: "The repo to sync labels on (defaults to current repo)"
    required: false
  token:
    description: "An alternative GitHub token to use instead"
    required: false
  prune:
    description: "Remove unmanaged labels from repository"
    required: false
    default: true
runs:
  using: "docker"
  image: "docker://ghcr.io/makeshift/action-label-syncer"
branding:
  icon: circle
  color: black
