name: CI
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Lint
        uses: golangci/golangci-lint-action@v6

      - name: Build
        run: go build cmd/action-label-syncer/main.go

      - name: Test
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
